# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/hi/Desktop/MD-Note/AV音视频&Hight高性能/h264_Nalu/Decode_H264"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/hi/Desktop/MD-Note/AV音视频&Hight高性能/h264_Nalu/Decode_H264"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/hi/Desktop/MD-Note/AV音视频&Hight高性能/h264_Nalu/Decode_H264/CMakeFiles" "/Users/hi/Desktop/MD-Note/AV音视频&Hight高性能/h264_Nalu/Decode_H264//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/hi/Desktop/MD-Note/AV音视频&Hight高性能/h264_Nalu/Decode_H264/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named a.out

# Build rule for target.
a.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 a.out
.PHONY : a.out

# fast build rule for target.
a.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/build
.PHONY : a.out/fast

AnnexBReader.o: AnnexBReader.cpp.o
.PHONY : AnnexBReader.o

# target to build an object file
AnnexBReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/AnnexBReader.cpp.o
.PHONY : AnnexBReader.cpp.o

AnnexBReader.i: AnnexBReader.cpp.i
.PHONY : AnnexBReader.i

# target to preprocess a source file
AnnexBReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/AnnexBReader.cpp.i
.PHONY : AnnexBReader.cpp.i

AnnexBReader.s: AnnexBReader.cpp.s
.PHONY : AnnexBReader.s

# target to generate assembly for a file
AnnexBReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/AnnexBReader.cpp.s
.PHONY : AnnexBReader.cpp.s

BitStream.o: BitStream.cpp.o
.PHONY : BitStream.o

# target to build an object file
BitStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/BitStream.cpp.o
.PHONY : BitStream.cpp.o

BitStream.i: BitStream.cpp.i
.PHONY : BitStream.i

# target to preprocess a source file
BitStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/BitStream.cpp.i
.PHONY : BitStream.cpp.i

BitStream.s: BitStream.cpp.s
.PHONY : BitStream.s

# target to generate assembly for a file
BitStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/BitStream.cpp.s
.PHONY : BitStream.cpp.s

EBSP.o: EBSP.cpp.o
.PHONY : EBSP.o

# target to build an object file
EBSP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/EBSP.cpp.o
.PHONY : EBSP.cpp.o

EBSP.i: EBSP.cpp.i
.PHONY : EBSP.i

# target to preprocess a source file
EBSP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/EBSP.cpp.i
.PHONY : EBSP.cpp.i

EBSP.s: EBSP.cpp.s
.PHONY : EBSP.s

# target to generate assembly for a file
EBSP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/EBSP.cpp.s
.PHONY : EBSP.cpp.s

Nalu.o: Nalu.cpp.o
.PHONY : Nalu.o

# target to build an object file
Nalu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Nalu.cpp.o
.PHONY : Nalu.cpp.o

Nalu.i: Nalu.cpp.i
.PHONY : Nalu.i

# target to preprocess a source file
Nalu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Nalu.cpp.i
.PHONY : Nalu.cpp.i

Nalu.s: Nalu.cpp.s
.PHONY : Nalu.s

# target to generate assembly for a file
Nalu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Nalu.cpp.s
.PHONY : Nalu.cpp.s

NaluPPS.o: NaluPPS.cpp.o
.PHONY : NaluPPS.o

# target to build an object file
NaluPPS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/NaluPPS.cpp.o
.PHONY : NaluPPS.cpp.o

NaluPPS.i: NaluPPS.cpp.i
.PHONY : NaluPPS.i

# target to preprocess a source file
NaluPPS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/NaluPPS.cpp.i
.PHONY : NaluPPS.cpp.i

NaluPPS.s: NaluPPS.cpp.s
.PHONY : NaluPPS.s

# target to generate assembly for a file
NaluPPS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/NaluPPS.cpp.s
.PHONY : NaluPPS.cpp.s

NaluSPS.o: NaluSPS.cpp.o
.PHONY : NaluSPS.o

# target to build an object file
NaluSPS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/NaluSPS.cpp.o
.PHONY : NaluSPS.cpp.o

NaluSPS.i: NaluSPS.cpp.i
.PHONY : NaluSPS.i

# target to preprocess a source file
NaluSPS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/NaluSPS.cpp.i
.PHONY : NaluSPS.cpp.i

NaluSPS.s: NaluSPS.cpp.s
.PHONY : NaluSPS.s

# target to generate assembly for a file
NaluSPS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/NaluSPS.cpp.s
.PHONY : NaluSPS.cpp.s

RBSP.o: RBSP.cpp.o
.PHONY : RBSP.o

# target to build an object file
RBSP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/RBSP.cpp.o
.PHONY : RBSP.cpp.o

RBSP.i: RBSP.cpp.i
.PHONY : RBSP.i

# target to preprocess a source file
RBSP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/RBSP.cpp.i
.PHONY : RBSP.cpp.i

RBSP.s: RBSP.cpp.s
.PHONY : RBSP.s

# target to generate assembly for a file
RBSP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/RBSP.cpp.s
.PHONY : RBSP.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... a.out"
	@echo "... AnnexBReader.o"
	@echo "... AnnexBReader.i"
	@echo "... AnnexBReader.s"
	@echo "... BitStream.o"
	@echo "... BitStream.i"
	@echo "... BitStream.s"
	@echo "... EBSP.o"
	@echo "... EBSP.i"
	@echo "... EBSP.s"
	@echo "... Nalu.o"
	@echo "... Nalu.i"
	@echo "... Nalu.s"
	@echo "... NaluPPS.o"
	@echo "... NaluPPS.i"
	@echo "... NaluPPS.s"
	@echo "... NaluSPS.o"
	@echo "... NaluSPS.i"
	@echo "... NaluSPS.s"
	@echo "... RBSP.o"
	@echo "... RBSP.i"
	@echo "... RBSP.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

