name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -B build
    - name: make
      run: cmake --build build -j 4
    - name: test1
      run: cd ./test && ../build/a.out ./demo_10_frames.h264 && ./test3.sh demo_10_frames.h264 && rm output_*.bmp
    - name: test2
      run: cd ./test && ../build/a.out ./demo_10_frames_cavlc.h264 && ./test3.sh demo_10_frames_cavlc.h264 && rm output_*.bmp
    - name: test3
      run: cd ./test && ../build/a.out ./source_cut_10_frames.h264 && ./test3.sh source_cut_10_frames.h264 && rm output_*.bmp
    - name: test4
      run: cd ./test && ../build/a.out ./source_cut_10_frames_no_B.h264 && ./test3.sh source_cut_10_frames_no_B.h264 && rm output_*.bmp
    - name: test5
      run: cd ./test && ../build/a.out ./demo_10_frames_cavlc_and_interlace.h264 && ./test3.sh demo_10_frames_cavlc_and_interlace.h264 && rm output_*.bmp
    - name: test6
      run: cd ./test && ../build/a.out 854x480_60_fps_50_gop_and_I_Slice.h264  && rm output_*.bmp


